# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: wholeinone-client
        repository: nh0317/wholeinone-client
        ref: master
    - run: cd wholeinone-client && npm install --legacy-peer-deps
    
    - uses: actions/checkout@v3
      with:
        path: wholeinone-server
    - run: ls
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x wholeinone-server/gradlew
    
    - name: Restore keystore
      run : echo $BASE64KEYSTORE | base64 -d > wholeinone-server/keystore.jks
      
      
    - name: Restore ssl-keystore
      run : echo $BASE64SSL | base64 -d > wholeinone-server/ssl-keystore.p12
    
    - name: Build with Gradle
      run: cd wholeinone-server && ./gradlew clean build -x test
    
    - name: put jar file
      # You may pin to the exact commit or the version.
      # uses: appleboy/scp-action@master
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_PROD }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PW }}
        port: 22
        source: "wholeinone-server/build/libs/*.jar"
        target: "/home/ec2-user/deploy"
        strip_components: 2
        
    - name: start server
      # You may pin to the exact commit or the version.
      # uses: appleboy/scp-action@master
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PROD }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PW }}
        port: 22
        script_stop: true
        script: chmod +x /home/ec2-user/deploy/backend_server.sh && sh /home/ec2-user/deploy/backend_server.sh
